---
name: PR Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install dependencies
      shell: bash
      run: >-
        sudo apt-get update &&
        sudo apt-get -y install gcc libgl1-mesa-dev xorg-dev libasound2-dev

    - name: Build
      run: go build -v ./
