---
name: PR Build

on:
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: "1.20"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Install dependencies
        shell: bash
        run: sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev

      - name: Build Linux executable
        shell: bash
        run: go build -o pixelmek-3d -v
